-- MySQL Script generated by MySQL Workbench
-- Seg 05 Dez 2016 16:30:17 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema maquina_de_alimentos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema maquina_de_alimentos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `maquina_de_alimentos` DEFAULT CHARACTER SET utf8 ;
USE `maquina_de_alimentos` ;

-- -----------------------------------------------------
-- Table `maquina_de_alimentos`.`tipo_alimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maquina_de_alimentos`.`tipo_alimento` (
  `id_tipo_alimento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `validade_dias` INT NOT NULL,
  `preco` DOUBLE NOT NULL,
  PRIMARY KEY (`id_tipo_alimento`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maquina_de_alimentos`.`maquina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maquina_de_alimentos`.`maquina` (
  `id_maquina` INT NOT NULL AUTO_INCREMENT,
  `cinquenta_centavo` INT NOT NULL DEFAULT 0,
  `um_real` INT NOT NULL DEFAULT 0,
  `dois_real` INT NOT NULL DEFAULT 0,
  `cinco_real` INT NOT NULL DEFAULT 0,
  `dez_real` INT NOT NULL,
  PRIMARY KEY (`id_maquina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maquina_de_alimentos`.`alimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maquina_de_alimentos`.`alimento` (
  `id_alimento` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_alimento` INT NOT NULL,
  `id_maquina` INT NOT NULL,
  `data_cadastro` TIMESTAMP NOT NULL,
  `bandeja` INT NOT NULL,
  INDEX `id_alimento_idx` (`id_tipo_alimento` ASC),
  INDEX `id_maquina_idx` (`id_maquina` ASC),
  PRIMARY KEY (`id_alimento`),
  CONSTRAINT `id_alimento`
    FOREIGN KEY (`id_tipo_alimento`)
    REFERENCES `maquina_de_alimentos`.`tipo_alimento` (`id_tipo_alimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_maquina`
    FOREIGN KEY (`id_maquina`)
    REFERENCES `maquina_de_alimentos`.`maquina` (`id_maquina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maquina_de_alimentos`.`operador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maquina_de_alimentos`.`operador` (
  `id_operador` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(300) NOT NULL,
  `login` VARCHAR(10) NOT NULL,
  `senha` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id_operador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maquina_de_alimentos`.`operador_maquina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maquina_de_alimentos`.`operador_maquina` (
  `id_operador` INT NOT NULL,
  `id_maquina` INT NOT NULL,
  INDEX `fk_operador_maquina_1_idx` (`id_operador` ASC),
  INDEX `fk_operador_maquina_2_idx` (`id_maquina` ASC),
  CONSTRAINT `fk_operador_maquina_1`
    FOREIGN KEY (`id_operador`)
    REFERENCES `maquina_de_alimentos`.`operador` (`id_operador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_operador_maquina_2`
    FOREIGN KEY (`id_maquina`)
    REFERENCES `maquina_de_alimentos`.`maquina` (`id_maquina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
